# Generated by Django 3.2.9 on 2021-11-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complet',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
